### ISSUE TITLE
integrate wiresteward with an existant wireguard server

### ISSUE THREAD

**Issue by UncleJ4ck** [utilitywarehouse/wiresteward#197]
Hi, i installed my wireguard server using a tool called: https://github.com/angristan/wireguard-install and im also managing my peers with it, im trying to add an oauth2 authentification to renforce security, and im finding it a bit complicated to do that if you have any guides or an existant documentation that i can rely on, i would be grateful.

Thanks
Regards,

**Comment by george-angel** [comment]
Hey! No documentation I'm afraid, but we have this Terraform module that you can probably reverse engineer to see how to run a server: https://github.com/utilitywarehouse/wiresteward/tree/master/terraform/ignition

**Comment by UncleJ4ck** [comment]
i will ask some noobie question so please withstand it !

i've read the README quite well and i understood that wiresteward works as an authentification manager that you can link it with an oauth2 server like keycloak and stuff...., so do i need to create a new server or there's an ability within wiresteward that does that or anything else because the documentation is a bit limited, i don't know from where i can start.

as i said i have a keycloak configured to be as an oauth2 server for authorization/authentication and i installed my wireguard vpn server using the script that i showed you in my first comment

**Comment by ffilippopoulos** [comment]
Let me try to explain a bit more how this works:
Wiresteward server expects the client to present a token and can validate that over an oauth introspect url in order to accept client requests. Then it does 3 things:
- Manages local (server) wireguard interfaces
- Adds new peers based on the client requests and manages them (it implements leases to kick peers out after some time for example)
- responds to clients with the needed configuration they need to configure their part in order to peer with the server
Wiresteward agent is running locally, let's say on your machine, and is the one that will take the user through the oauth2 dance to obtain a token from the oauth server (careful that for this the oauth2 server must accept redirection to localhost). Then it will reach out to the server with that token and public info about the local wireguard interfaces to request the server config in order to peer.
Both in server and agent mode, wiresteward is expecting to manage local wireguard interfaces.

> wiresteward works as an authentification manager that you can link it with an oauth2 server
On server mode you can link wiresteward to an oauth2 server introspection url to validate tokens. The agent will also need to be linked to the same oauth2 server in order to obtain the token to use in requests to weiresteward server.

**Comment by UncleJ4ck** [comment]
alright thanks for the clarification !
